services:
  db:
    image: postgres:16-alpine
    container_name: ticket-db
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_user -d ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
